Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('//content/creditcard.csv')

In [ ]:
# first 5 rows of the dataset
credit_card_data.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
53566,46047,-2.885416,-2.647887,1.903441,3.726885,3.800798,-1.644480,-1.924198,0.707696,-1.070468,...,0.284893,-0.268122,0.977417,0.136853,-1.144367,-0.535616,0.098494,0.305740,19.02,0.0
53567,46048,1.061410,0.045830,0.970401,1.102883,-0.490685,0.219968,-0.424285,0.235960,0.016498,...,0.033158,0.067127,0.053801,-0.010221,0.209877,-0.484136,0.057583,0.028018,28.70,0.0
53568,46048,-0.202740,0.295074,1.924698,1.009344,-0.235931,-0.272232,0.261015,-0.162146,-0.583849,...,0.321731,1.056540,0.093902,0.608566,-0.931546,0.466156,0.016695,-0.024568,54.81,0.0
53569,46048,-0.730116,0.796820,2.122484,-1.318082,0.019762,-0.857857,0.975752,-0.399896,0.359189,...,-0.149736,0.093479,-0.056586,0.650087,-0.473889,0.662115,0.060486,-0.208536,4.53,0.0
53570,46050,0.791672,-0.522991,0.036747,1.204803,-0.262390,-0.056153,0.263614,-0.130209,0.125423,...,0.013131,-0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53571 entries, 0 to 53570
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    53571 non-null  int64
 1   V1      53571 non-null  float64
 2   V2      53571 non-null  float64
 3   V3      53571 non-null  float64
 4   V4      53571 non-null  float64
 5   V5      53571 non-null  float64
 6   V6      53571 non-null  float64
 7   V7      53571 non-null  float64
 8   V8      53571 non-null  float64
 9   V9      53571 non-null  float64
 10  V10     53571 non-null  float64
 11  V11     53571 non-null  float64
 12  V12     53571 non-null  float64
 13  V13     53571 non-null  float64
 14  V14     53571 non-null  float64
 15  V15     53571 non-null  float64
 16  V16     53571 non-null  float64
 17  V17     53571 non-null  float64
 18  V18     53571 non-null  float64
 19  V19     53571 non-null  float64
 20  V20     53571 non-null  float64
 21  V21     53571 non-null  float64
 22  V22     53571 non-null  float64
 23  V23     53570 non-null  float64
 24  V24     53570 non-null  float64
 25  V25     53570 non-null  float64
 26  V26     53570 non-null  float64
 27  V27     53570 non-null  float64
 28  V28     53570 non-null  float64
 29  Amount  53570 non-null  float64
 30  Class   53570 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 12.7 MB

In [6]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [7]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    53417
1.0      153
Name: count, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [8]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [9]:
print(legit.shape)
print(fraud.shape)

(53417, 31)
(153, 31)

In [10]:
# statistical measures of the data
legit.Amount.describe()

count    53417.000000
mean        94.251260
std        252.353693
min          0.000000
25%          7.680000
50%         25.520000
75%         86.650000
max      12910.930000
Name: Amount, dtype: float64

In [11]:
fraud.Amount.describe()

count     153.000000
mean       97.616013
std       230.026856
min         0.000000
25%         1.000000
50%         7.610000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [12]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,30011.81811,-0.222505,-0.014659,0.722511,0.163565,-0.242775,0.109604,-0.097131,0.042665,0.104805,...,0.046251,-0.031568,-0.106396,-0.038408,0.008094,0.134794,0.019825,0.002289,0.003902,94.251260
1.0,27472.24183,-7.468948,5.326389,-10.100308,5.793812,-5.528864,-2.230554,-7.865700,3.617647,-3.492917,...,0.455720,0.891045,-0.218399,-0.277419,-0.084305,0.240593,0.136258,0.586389,0.028185,97.616013

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [13]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [14]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [15]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
40006,40054,-1.642452,0.978451,1.893787,1.073778,-0.919048,0.184649,-0.961998,1.202414,-0.108587,...,0.156416,0.219307,-0.246397,0.061092,0.104221,-0.242205,-0.193692,-0.125066,1.00,0.0
29931,35701,-1.443665,0.543987,1.467014,1.090871,0.398274,-0.647077,0.251767,0.214343,-1.017700,...,0.173538,0.343703,-0.324101,0.353821,0.437371,-0.207563,-0.357161,-0.225855,12.34,0.0
845,646,-0.916848,1.471812,0.742995,-0.131084,0.518566,0.772582,-0.342258,-2.248702,-0.574626,...,2.114718,-1.311987,0.155953,-1.070769,-0.454872,0.186908,0.227996,0.152385,1.79,0.0
6187,7209,-0.395061,1.220049,1.344753,1.241180,0.197627,-0.812807,0.319639,-0.250380,0.675997,...,-0.333152,-0.523781,0.059540,0.326634,-0.846261,0.198088,0.289482,0.230902,4.49,0.0
30367,35890,1.036894,-0.342870,0.511651,0.718177,-0.373640,0.634078,-0.451355,0.398545,0.572910,...,0.019982,0.201198,-0.048786,-0.264932,0.346657,0.482121,-0.001763,-0.004228,36.00,0.0

In [16]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
50211,44393,-4.617461,3.663395,-5.297446,3.880960,-3.263551,-0.918547,-5.715262,0.831040,-2.457034,...,2.698175,-0.027081,0.366775,-0.123011,-0.300457,-0.239996,-0.183463,-0.073360,1.00,1.0
50537,44532,-0.234922,0.355413,1.972183,-1.255593,-0.681387,-0.665732,0.059110,-0.003153,1.122451,...,0.220670,0.912107,-0.286338,0.451208,0.188315,-0.531846,0.123185,0.039581,1.00,1.0
52466,45463,-1.476893,2.122314,-1.229470,1.201849,-0.343264,-1.317704,-1.528142,-0.620953,-1.213040,...,1.186036,-0.040215,-0.238930,0.110144,0.045418,-0.569232,0.481019,-0.047555,1.00,1.0
52521,45501,1.001992,0.047938,-0.349002,1.493958,0.186939,0.190966,-0.001112,0.147140,0.580415,...,-0.334417,-1.014315,-0.128427,-0.946242,0.456090,-0.453206,0.046627,0.064698,105.99,1.0
52584,45541,-1.519244,2.308492,-1.503599,2.064101,-1.000845,-1.016897,-2.059731,-0.275166,-1.562206,...,1.307871,0.102826,-0.017746,0.149696,-0.096602,-0.369115,-0.019244,-0.208319,1.00,1.0

In [17]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0    153
Name: count, dtype: int64

In [18]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,29545.351626,-0.233958,-0.065161,0.775578,0.124038,-0.210524,0.127577,-0.049851,-0.024142,0.055764,...,0.101597,-0.055700,-0.122733,-0.002622,0.007243,0.117837,0.027306,0.025299,0.013516,101.678028
1.0,27472.241830,-7.468948,5.326389,-10.100308,5.793812,-5.528864,-2.230554,-7.865700,3.617647,-3.492917,...,0.455720,0.891045,-0.218399,-0.277419,-0.084305,0.240593,0.136258,0.586389,0.028185,97.616013

Splitting the data into Features & Targets

In [19]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [20]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
40006  40054 -1.642452  0.978451  1.893787  1.073778 -0.919048  0.184649
29931  35701 -1.443665  0.543987  1.467014  1.090871  0.398274 -0.647077
845      646 -0.916848  1.471812  0.742995 -0.131084  0.518566  0.772582
6187    7209 -0.395061  1.220049  1.344753  1.241180  0.197627 -0.812807
30367  35890  1.036894 -0.342870  0.511651  0.718177 -0.373640  0.634078
...      ...       ...       ...       ...       ...       ...       ...
50211  44393 -4.617461  3.663395 -5.297446  3.880960 -3.263551 -0.918547
50537  44532 -0.234922  0.355413  1.972183 -1.255593 -0.681387 -0.665732
52466  45463 -1.476893  2.122314 -1.229470  1.201849 -0.343264 -1.317704
52521  45501  1.001992  0.047938 -0.349002  1.493958  0.186939  0.190966
52584  45541 -1.519244  2.308492 -1.503599  2.064101 -1.000845 -1.016897

             V7        V8        V9  ...       V20       V21       V22  \
40006 -0.961998  1.202414 -0.108587  ... -0.322525  0.156416  0.219307
29931  0.251767  0.214343 -1.017700  ...  0.146979  0.173538  0.343703
845   -0.342258 -2.248702 -0.574626  ... -0.402461  2.114718 -1.311987
6187   0.319639 -0.250380  0.675997  ...  0.273064 -0.333152 -0.523781
30367 -0.451355  0.398545  0.572910  ... -0.213090  0.019982  0.201198
...         ...       ...       ...  ...       ...       ...       ...
50211 -5.715262  0.831040 -2.457034  ... -0.346456  2.698175 -0.027081
50537  0.059110 -0.003153  1.122451  ... -0.003469  0.220670  0.912107
52466 -1.528142 -0.620953 -1.213040  ...  0.276893  1.186036 -0.040215
52521 -0.001112  0.147140  0.580415  ...  0.016004 -0.334417 -1.014315
52584 -2.059731 -0.275166 -1.562206  ...  0.175019  1.307871  0.102826

            V23       V24       V25       V26       V27       V28  Amount
40006 -0.246397  0.061092  0.104221 -0.242205 -0.193692 -0.125066    1.00
29931 -0.324101  0.353821  0.437371 -0.207563 -0.357161 -0.225855   12.34
845    0.155953 -1.070769 -0.454872  0.186908  0.227996  0.152385    1.79
6187   0.059540  0.326634 -0.846261  0.198088  0.289482  0.230902    4.49
30367 -0.048786 -0.264932  0.346657  0.482121 -0.001763 -0.004228   36.00
...         ...       ...       ...       ...       ...       ...     ...
50211  0.366775 -0.123011 -0.300457 -0.239996 -0.183463 -0.073360    1.00
50537 -0.286338  0.451208  0.188315 -0.531846  0.123185  0.039581    1.00
52466 -0.238930  0.110144  0.045418 -0.569232  0.481019 -0.047555    1.00
52521 -0.128427 -0.946242  0.456090 -0.453206  0.046627  0.064698  105.99
52584 -0.017746  0.149696 -0.096602 -0.369115 -0.019244 -0.208319    1.00

[645 rows x 30 columns]

In [21]:
print(Y)

40006    0.0
29931    0.0
845      0.0
6187     0.0
30367    0.0
        ...
50211    1.0
50537    1.0
52466    1.0
52521    1.0
52584    1.0
Name: Class, Length: 645, dtype: float64

Split the data into Training data & Testing Data

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [23]:
print(X.shape, X_train.shape, X_test.shape)

(645, 30) (516, 30) (129, 30)

Model Training

Logistic Regression

In [24]:
model = LogisticRegression()

In [25]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [26]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [27]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9748062015503876

In [28]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [29]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9767441860465116

In [30]:
import pickle

# Save the trained model
with open("model.pkl", "wb") as file:
    pickle.dump(model, file)

print("Model saved successfully!")

Model saved successfully!

In [31]:
from google.colab import files

files.download("model.pkl")